# Generated by Django 5.2.3 on 2025-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product",
            new_name="sneaker",
        ),
    ]
