# Generated by Django 5.2.3 on 2025-07-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sneakers", "0002_sneaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sneaker",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
